# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a115282cdf1e9525f6b271fd186f4338dc6b95c8ba08d393ac975a40565c6492e2fc890e673ff0e516fdea8bddde3ebcce74bff9f59d134877743604e0389110

test:
  secret_key_base: ec28c2b8d78e0d54b38e34b2a8c6550ff77224c8f286f48200fd6f3617abc62f7aca16db9898bc522021b4935a0e1c9c28eea4807a6f0c788ff55b7ceed48024

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
